# By Harsh H. Rajpurohit
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.2+2

environment:
  sdk: ">=3.4.3 <4.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter
  
  # Cupertino style icons
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  # change_app_package_name: ^1.3.0

  # Encourages good practices
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/icons/