# By DucThanhNguyen
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.2+2

environment:
  sdk: ">=3.4.3 <4.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter
  
  # Cupertino style icons
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  http: ^1.2.2
  csv: ^6.0.0
  lottie: ^3.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.0.2
  google_mobile_ads: ^5.2.0
  firebase_core: ^3.8.0
  firebase_remote_config: ^5.1.5
  intl: ^0.20.2
  flutter_svg: ^2.0.17


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  # change_app_package_name: ^1.3.0

  # Encourages good practices
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0

flutter:
  # Enabling material design
  uses-material-design: true
  generate: true
  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/flags/
    - assets/svg/
    - .env