# Tăng bộ nhớ Gradle cho build
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError

# Bật chế độ song song, tăng tốc build
org.gradle.parallel=true
org.gradle.configureondemand=true

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Bật buildFeatures cần thiết
android.defaults.buildfeatures.aidl=true
android.useAapt2=true

# R8 thay thế ProGuard
android.enableR8=true

 

# Java 17 (đồng bộ với app/build.gradle)
android.compileOptions.sourceCompatibility=17
android.compileOptions.targetCompatibility=17
kotlin.jvm.target=17

# NDK r28 để build 16KB page size
android.ndkVersion=28.0.12674087
