[Interface]
Address = 10.7.0.2/24, fddd:2c4:2c4:2c4::2/64
DNS = 1.1.1.1, 1.0.0.1
PrivateKey = eF16z+HK3xJWrrn4WrQ6xwn00bmgyhZlf8VagvkeYn4=

[Peer]
PublicKey = t44oGhwGAakFjPXvyJatiSlUg4V/k75VEqG4z8eXbjg=
PresharedKey = qufit1jtRdXOB6mkUSsOmfreyhDcBLaQaAB+khfAfk0=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 127.0.0.1:51820
PersistentKeepalive = 25
